baseURL = 'https://docs.agopengps.com/'
languageCode = 'en-us'
title = 'AgOpenGPS Documentation'

[params]
  github_repo = "https://github.com/AgOpenGPS-Official/AgOpenGPS-Documentation"
  github_project_repo = "https://github.com/AgOpenGPS-Official/AgOpenGPS"
  offlineSearch = true
  [params.ui]
    showLightDarkModeMenu = true
    breadcrumb_disable = true
    taxonomy_breadcrumb_disable = true
    sidebar_search_disable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
