site_name: AgOpenGPS Documentation

nav:
  - Home: index.md
  - Software:
    - What is AgOpenGPS?: software/01.-What-is-AgOpenGPS?.md
    - Install AgOpenGPS and AgIO: software/02.-Install-AgOpenGPS-and-AgIO.md
    - AgIO Orientation: software/03.-AgIO-Orientation.md
    - AgOpenGPS Orientation: software/04.-AgOpenGPS-Orientation.md
    - Ethernet Setup: software/05.-Ethernet-Setup.md
    - RTK Setup: software/06.-RTK-Setup.md
    - UDP Monitor: software/07.-UDP-Monitor.md
    - Serial Monitor: software/08.-Serial-Monitor.md
    - ChangeLog: software/ChangeLog.md
    - FAQ: software/FAQ.md
  - Hardware:
    - '"My tractor has X, how to steer it"': hardware/kits.md
    - Hardware that's needed: hardware/tl-dr-cut-to-the-chase-what-do-i-buy.md
    - Boards - All-In-One:
      - All-In-One Board versions and how to order:
        - hardware/AIO-Board-flavours/index.md
        - AIO v2.x issues and fixes: hardware/AIO-Board-flavours/v2.x-board-issues---fixes.md
        - AIO v4.x issues and fixes: hardware/AIO-Board-flavours/v4.x-AIO-board-issues-and-fixes.md
      - Assembling the board:
        - hardware/assemblingtheboard/index.md
        - Components you can do without: hardware/assemblingtheboard/components-you-can-do-without.md
        - Electrical testing and validation: hardware/assemblingtheboard/electrical-testing-and-validation.md
        - Reading LEDs: hardware/assemblingtheboard/Reading-LEDs.md
      - Other pieces to be able to assemble: hardware/AIO-other-pieces.md
      - Ampseal 23 pinout: hardware/AIO-Board-Pinout.md
      - Ampseal-Wiring-Harness example: hardware/AIO--Ampseal-Wiring-Harness.md
    - Boards - Others:
      - Brians old board: hardware/02-Build-Version-2-Steer-Board.md
      - Legacy solutions: https://github.com/AgOpenGPS-Official/Boards/tree/main/ArduinoModules
      - Enclosures: hardware/Enclosures.md
    - Implement Boards:
      - Machine Board for relay control: hardware/Machine-Board.md
      - Machine board - full guide: hardware/Machineboardguide.md
      - Rate Controller for variable rate and section: https://github.com/SK21/AOG_RC
    - Other components:
      - GNSS / GPS - ZED-F9P: hardware/gps-modules-standard-or-micro.md
      - GNSS Antenna: hardware/Choosing-an-Antenna.md
      - Teensy 4.1 a.k.a the brain of the board: hardware/teensy-4.1.md
      - IMU for roll compensation: hardware/imu-inertial-measurement-unit.md
      - Wheel Angle Sensor: hardware/wheel-angle-sensor.md
      - Windows Tablet: hardware/tablet.md
      - Cytron MD13S driver: hardware/cytron-motor-driver.md
      - Steering with Motor: hardware/the-motor.md
      - Steering with Baraki hydraulic block: hardware/Hydraulic-steering-with-baraki-valve.md
      - Steering via CAN bus: hardware/CANBUS.md
      - Steering via Danfoss: hardware/Danfoss.md
      - Steering with Keya CANBUS wheel: hardware/Keya.md
      - Connectors:
        - hardware/Connectors/index.md
        - Connector Accessories: hardware/Connectors/Connector-Accessories.md
      - Cabling and Wiring: hardware/CablingWiring.md
      - Miscellaneous hardware: hardware/MiscHardware.md
    - Boards - Configuration:
      - Configuring the ZED-F9P GPS: hardware/configuring-the-zed-f9p.md
      - Configuring the Teensy: hardware/Configuring-The-Teensy.md
      - Configuring your tablet: hardware/configuring-your-tablet.md
    - Suppliers of full systems: hardware/suppliers.md
    - SCAMMERS: hardware/SCAMMERS.md
    - Networking:
      - hardware/networking/index.md
      - Ethernet Setup: software/05.-Ethernet-Setup.md
    - Video Guides: hardware/videoguides.md
    - 🤩 AgOpenGPS - a guide for machine-users: software/04.-AgOpenGPS-Orientation.md
    - 🚜 The Manual: hardware/TheManual.md
    - 🤯 Frequently Asked Questions:
      - hardware/FAQ/index.md
      - Help! I need to speak to someone!: hardware/FAQ/help-i-need-to-speak-to-someone.md
      - Is AGIO running? AgIO?: hardware/FAQ/is-agio-running-agio.md
      - UDP: hardware/FAQ/udp.md
      - RTK/NTRIP corrections: hardware/FAQ/rtk-ntrip-corrections.md
      - Serial/COM ports: hardware/FAQ/serial-com-ports.md
      - Swapping GPS ports: hardware/FAQ/swapping-gps-ports.md
    - 🤬 Problems and Solutions: hardware/ProblemsAndSolutions.md
    - Other cool open-source Ag projects: hardware/otherprojects.md
    - 3D prints and designs: hardware/3dprints.md
    - Other references: hardware/otherrefs.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
