name: Links (Deployed Site)

on:
  schedule:
    - cron: '15 18 * * *' # run after your build cron; stagger by 15m
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    env:
      SITE_URL: https://jamesdsmith212.github.io/AgOpenGPS-Documentation/
    steps:
      - name: Create lychee directory
        run: mkdir -p lychee

      - name: Check deployed site links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          output: ./lychee/out.md
          args: >-
            --no-progress --verbose --cache --max-cache-age 1d --retry-wait-time
            2 --max-retries 2 $SITE_URL

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report (Deployed Site)
          content-filepath: ./lychee/out.md
          labels: report, automated issue
